export const BicepExcerciseData = [
  {
    name: "dumbbellBicepCurlOrBicepCurl",
    displayName: "Dumbbell Bicep Curl or Bicep Curl",
    img: "https://www.inspireusafoundation.org/wp-content/uploads/2023/01/inner-bicep-curl.gif",
    excerciseData: [],
  },
  {
    name: "hammerCurl",
    displayName: "Hammer Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif",
    excerciseData: [],
  },
  {
    name: "inclineDumbbellCurl",
    displayName: "Incline Dumbbell Curl",
    img: "https://i.pinimg.com/originals/b4/30/64/b43064d9ad9f42493dbcf37e653ab87c.gif",
    excerciseData: [],
  },
  {
    name: "concentrationCurl",
    displayName: "Concentration Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Concentration-Curl.gif",
    excerciseData: [],
  },
  {
    name: "barbellCurl",
    displayName: "Barbell Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif",
    excerciseData: [],
  },
  {
    name: "barbellPreacherCurl",
    displayName: "Barbell Preacher Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Z-Bar-Preacher-Curl.gif",
    excerciseData: [],
  },
  {
    name: "overheadCableCurl",
    displayName: "Overhead cable curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/04/overhead-cable-curl.gif",
    excerciseData: [],
  },
  {
    name: "zottmanCurl",
    displayName: "Zottman curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/04/zottman-curl.gif",
    excerciseData: [],
  },
  {
    name: "ezBarCurl",
    displayName: "Ez-bar Curl",
    img: "https://gymvisual.com/img/p/7/2/9/5/7295.gif",
    excerciseData: [],
  },
  {
    name: "ezBarPreacherCurl",
    displayName: "Ez-bar Preacher Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Z-Bar-Preacher-Curl.gif",
    excerciseData: [],
  },
  {
    name: "reverseBarbellCurl",
    displayName: "Reverse barbell curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Reverse-Curl.gif",
    excerciseData: [],
  },
  {
    name: "cableRopeHammerCurl",
    displayName: "Cable Rope Hammer Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/06/rope-bicep-curls.gif",
    excerciseData: [],
  },
  {
    name: "spiderCurl",
    displayName: "Spider curl",
    img: "https://static1.squarespace.com/static/5e9f8e841520b34d121c63f2/6100b659f4d09d4ead11d54f/621ada7a4fa9355152d7ca0c/1709015689297/00721301-Barbell-Prone-Incline-Curl_Upper-Arms_720.gif?format=1500w",
    excerciseData: [],
  },
  {
    name: "waiterCurl",
    displayName: "Waiter Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2023/09/waiter-curl.gif",
    excerciseData: [],
  },
  {
    name: "oneArmDumbbellPreacherCurl",
    displayName: "One Arm Dumbbell Preacher Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Preacher-Curl.gif",
    excerciseData: [],
  },
  {
    name: "wideGripStandingBarbellCurl",
    displayName: "Wide-grip Standing Barbell Curl",
    img: "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/wide-grip-ez-bar-curl.gif",
    excerciseData: [],
  },
  {
    name: "machinePreacherCurl",
    displayName: "Machine Preacher Curl",
    img: "https://fitnessprogramer.com/wp-content/uploads/2021/04/Lever-Preacher-Curl.gif",
    excerciseData: [],
  },
  {
    name: "preacherHammerDumbbellCurl",
    displayName: "Preacher Hammer Dumbbell curl",
    img: "https://newlife.com.cy/wp-content/uploads/2019/11/04021301-Dumbbell-Seated-Preacher-Curl_Upper-Arms_360.gif",
    excerciseData: [],
  },
  {
    name: "inclineHammerCurl",
    displayName: "Incline hammer curl",
    img: "https://gymvisual.com/img/p/5/0/4/8/5048.gif",
    excerciseData: [],
  },
  {
    name: "inclineDumbbellPress",
    displayName: "Incline dumbbell press",
    img: "https://boxlifemagazine.com/wp-content/uploads//2023/06/image-4.gif",
    excerciseData: [],
  },
];
